namespace :casts do
  desc "Seed casts"
  task casts: :environment do
    roles = Role.all

    casts_data = [
      # added actors
      {first_name: "Richard", last_name: "Gere", date_of_birth: "1949-08-31", description: "American actor. Golden Globe Award winner and Emmy Award nominee.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Julia", last_name: "Roberts", date_of_birth: "1967-10-28", description: "American film actor and producer, the most popular actor in the world (2002-2005). Winner of three Golden Globes with 8 nominations, nominee for four Academy Awards, winner of the Oscar Award from the US Academy of Film Science for her work in the film \"Erin Brockovich\".", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Leonardo", last_name: "DiCaprio", date_of_birth: "1974-11-11", description: "American actor and film producer. Known for his work in biographical and period films, he is the recipient of numerous accolades, including an Academy Award, a British Academy Film Award, and three Golden Globe Awards.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Kate", last_name: "Winslet", date_of_birth: "1975-10-05", description: "English actress. Known for her roles as headstrong and complicated women in independent films, particularly period dramas, she has received numerous accolades, including an Academy Award, a Grammy Award, two Primetime Emmy Awards, five BAFTA Awards and five Golden Globe Awards.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Zoe", last_name: "Saldana", date_of_birth: "1978-06-19", description: "American actress. Known primarily for her work in science fiction film franchises, she has starred in four of the highest-grossing films of all time (Avatar, Avatar: The Way of Water, Avengers: Infinity War, and Avengers: Endgame).", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Sam", last_name: "Worthington", date_of_birth: "1976-08-02", description: "Australian actor. He is known for playing Jake Sully in the Avatar franchise, Marcus Wright in Terminator Salvation, and Perseus in Clash of the Titans and its sequel Wrath of the Titans.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Sigourney", last_name: "Weaver", date_of_birth: "1949-10-08", description: "American actress. A figure in science fiction and popular culture, she has received various accolades, including a British Academy Film Award, two Golden Globe Awards, and a Grammy Award, in addition to nominations for three Academy Awards, four Primetime Emmy Awards, and a Tony Award.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Jennifer", last_name: "Lawrence", date_of_birth: "1990-08-15", description: "American actress. She is known for starring in both action film franchises and independent dramas, and her films have grossed over $6 billion worldwide.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Meryl", last_name: "Streep", date_of_birth: "1949-06-22", description: "American actress. Known for her versatility and accent adaptability, she has been described as \"the best actress of her generation\".", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Anne", last_name: "Hathaway", date_of_birth: "1982-11-12", description: "American actress. Her accolades include an Academy Award, a British Academy Film Award, a Golden Globe Award, and a Primetime Emmy Award.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Brad", last_name: "Pitt", date_of_birth: "1963-12-18", description: "American actor and film producer. He is the recipient of various accolades, including two Academy Awards, two British Academy Film Awards, two Golden Globe Awards, and a Primetime Emmy Award.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Angelina", last_name: "Jolie", date_of_birth: "1975-06-04", description: "American actress, filmmaker, and humanitarian. The recipient of numerous accolades, including an Academy Award and three Golden Globe Awards, she has been named Hollywood's highest-paid actress multiple times.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Daniel", last_name: "Craig", date_of_birth: "1968-05-02", description: "English actor. He gained international fame by playing the fictional secret agent James Bond for five installments in the film series, from Casino Royale (2006) up to No Time to Die (2021).", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Gerard", last_name: "Butler", date_of_birth: "1969-11-13", description: "Scottish actor and film producer. After studying law, he turned to acting in the mid-1990s with small roles in productions such as Mrs Brown (1997), the James Bond film Tomorrow Never Dies (1997), and Tale of the Mummy (1998).", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Monica", last_name: "Bellucci", date_of_birth: "1964-09-30", description: "Italian actress and model who began her career as a fashion model before working in Italian, American and French films. Bellucci has an eclectic filmography in a range of genres and languages, and her accolades include the David di Donatello, Globo d'oro and Nastro d'Argento awards.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Sam", last_name: "Neill", date_of_birth: "1974-09-14", description: "New Zealand actor. Neill's career has included leading roles in both dramas and blockbusters. Considered an \"international leading man\", he has been regarded as one of the most versatile actors of his generation.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Laura", last_name: "Dern", date_of_birth: "1967-02-10", description: "American actress. She is the recipient of numerous accolades, including an Academy Award, a Primetime Emmy Award, a BAFTA Award, and five Golden Globe Awards.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Richard", last_name: "Attenborough", date_of_birth: "1923-08-29", description: "English actor, film director and producer, who was the president of the Royal Academy of Dramatic Art (RADA) and the British Academy of Film and Television Arts (BAFTA), as well as life president of the Premier League club Chelsea.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Arnold", last_name: "Schwarzenegger", date_of_birth: "1947-07-30", description: "Austrian and American actor, businessman, filmmaker, former politician, and former professional bodybuilder known for his roles in high-profile action movies.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Michael", last_name: "Biehn", date_of_birth: "1956-07-31", description: "American actor, primarily known for his roles in science fiction films directed by James Cameron; as Sgt. Kyle Reese in The Terminator (1984), Cpl. Dwayne Hicks in Aliens (1986), and Lt. Coffey in The Abyss (1989).", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Linda", last_name: "Hamilton", date_of_birth: "1956-09-26", description: "American actress. Known for portraying tough, resilient characters, she made her film debut in 1979 before achieving fame with her starring role as Sarah Connor in The Terminator (1984) and two of its sequels, Terminator 2: Judgment Day (1991) and Terminator: Dark Fate (2019).", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Emma", last_name: "Watson", date_of_birth: "1990-04-15", description: "English actress. Known for her roles in both blockbusters and independent films, she has received a selection of accolades, including a Young Artist Award and three MTV Movie Awards.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Dan", last_name: "Stevens", date_of_birth: "1982-10-10", description: "English actor. He first drew international attention for his role as Matthew Crawley in the ITV acclaimed period drama series Downton Abbey (2010–2012).", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Luke", last_name: "Evans", date_of_birth: "1979-04-15", description: "Welsh actor and singer. He began his career on the stage, and performed in London's West End productions of Rent, Miss Saigon, and Piaf before making his film breakthrough in the Clash of the Titans 2010 remake.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Daniel", last_name: "Radcliffe", date_of_birth: "1989-07-23", description: "English actor. He rose to fame at age 12 when he began portraying Harry Potter in the film series of the same name.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Rupert", last_name: "Grint", date_of_birth: "1988-08-24", description: "English actor. Grint rose to fame for his role as Ron Weasley in the Harry Potter film series, for which he was cast at age eleven, having previously acted only in school plays and his local theatre group.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Johnny", last_name: "Depp", date_of_birth: "1963-06-09", description: "American actor and musician. He is the recipient of multiple accolades, including a Golden Globe Award as well as nominations for three Academy Awards and two BAFTA awards.", role_id: roles.find_by(title: "Actor").id},
      {first_name: "Freddie", last_name: "Highmore", date_of_birth: "1992-02-14", description: "English actor. He is known for his starring roles beginning as a child, in the films Finding Neverland (2004), Charlie and the Chocolate Factory (2005), Arthur and the Invisibles (2006), August Rush (2007), and The Spiderwick Chronicles (2008).", role_id: roles.find_by(title: "Actor").id},
      # added film directors
      {first_name: "Garry", last_name: "Marshall", date_of_birth: "1934-11-13", description: "American screenwriter, film director, producer and actor. Marshall began his career in the 1960s as a writer for The Lucy Show and The Dick Van Dyke Show until he developed the television adaptation of Neil Simon's play The Odd Couple.", role_id: roles.find_by(title: "Film director").id},
      {first_name: "James", last_name: "Cameron", date_of_birth: "1954-08-16", description: "Canadian filmmaker. He is a major figure in the post-New Hollywood era. He often uses novel technologies with a classical filmmaking style.", role_id: roles.find_by(title: "Film director").id},
      {first_name: "Adam", last_name: "McKay", date_of_birth: "1968-04-17", description: "American screenwriter, producer, and director. McKay began his career as a head writer for the NBC sketch comedy show Saturday Night Live (SNL) from 1995 to 2001.", role_id: roles.find_by(title: "Film director").id},
      {first_name: "David", last_name: "Frankel", date_of_birth: "1959-04-02", description: "American filmmaker. He directed the 2006 film The Devil Wears Prada, as well as Marley & Me (2008), Hope Springs (2012), Jerry & Marge Go Large (2022), and the first and fourth episodes of the Netflix miniseries Inventing Anna (2022).", role_id: roles.find_by(title: "Film director").id},
      {first_name: "Doug", last_name: "Liman", date_of_birth: "1965-07-24", description: "American film director and producer. He is known for directing the films Swingers (1996), Go (1999), The Bourne Identity (2002), Mr. & Mrs. Smith (2005), Jumper (2008), Edge of Tomorrow (2014), and American Made (2017).", role_id: roles.find_by(title: "Film director").id},
      {first_name: "Simon", last_name: "West", date_of_birth: "1961-07-17", description: "English film director and producer. He has primarily worked in the action genre, most notably as the director of the films Con Air, Lara Croft: Tomb Raider, The Mechanic, and The Expendables 2.", role_id: roles.find_by(title: "Film director").id},
      {first_name: "Jan", last_name: "De Bont", date_of_birth: "1943-10-22", description: "Dutch retired cinematographer, director and film producer. He is best known for directing the films Speed (1994) and Twister (1996).", role_id: roles.find_by(title: "Film director").id},
      {first_name: "Sam", last_name: "Mendes", date_of_birth: "1965-08-01", description: "British film and stage director, producer, and screenwriter. In 2000, Mendes was appointed a CBE for his services to drama, and he was knighted in the 2020 New Years Honours List.", role_id: roles.find_by(title: "Film director").id},
      {first_name: "Steven", last_name: "Spielberg", date_of_birth: "1946-12-18", description: "American filmmaker. A major figure of the New Hollywood era and pioneer of the modern blockbuster, he is the most commercially successful director in history.", role_id: roles.find_by(title: "Film director").id},
      {first_name: "Bill", last_name: "Condon", date_of_birth: "1955-10-22", description: "American director and screenwriter. Condon is known for writing and/or directing numerous successful and acclaimed films including Gods and Monsters, Chicago, Kinsey, Dreamgirls and others.", role_id: roles.find_by(title: "Film director").id},
      {first_name: "Chris", last_name: "Columbus", date_of_birth: "1958-09-10", description: "American filmmaker, who gained recognition soon after with the highly successful Christmas comedy Home Alone (1990) and Home Alone 2: Lost in New York (1992).", role_id: roles.find_by(title: "Film director").id},
      {first_name: "Tim", last_name: "Burton", date_of_birth: "1958-08-25", description: "American director, producer, writer, and animator. Known for pioneering goth culture in the American film industry, Burton is famous for his gothic horror and fantasy films.", role_id: roles.find_by(title: "Film director").id},
      {first_name: "Lasse", last_name: "Hallström", date_of_birth: "1946-06-02", description: "Swedish film director. He first became known for directing almost all the music videos by the pop group ABBA, and subsequently became a feature film director.", role_id: roles.find_by(title: "Film director").id}
    ]

    Cast.create(casts_data)

    puts "Casts inserted successfully!"
  end
end
